version: '3.8'

services:
  auth:
    build:
      context: ./backend/authService
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
  streaming:
    build:
      context: ./backend/streamingService
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - auth
      - streaming

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: abhash
      MONGO_INITDB_ROOT_PASSWORD: abhash_pass

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: abhash
      ME_CONFIG_MONGODB_ADMINPASSWORD: abhash_pass
      ME_CONFIG_MONGODB_URL: mongodb://abhash:abhash_pass@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  